# Generated by Django 3.1.7 on 2021-03-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ogc_fid', models.IntegerField(blank=True, null=True)),
                ('station_id', models.IntegerField(blank=True, db_column='station id', null=True)),
                ('complex_id', models.CharField(blank=True, db_column='complex id', max_length=5, null=True)),
                ('gtfs_stop_id', models.CharField(blank=True, db_column='gtfs stop id', max_length=5, null=True)),
                ('division', models.CharField(blank=True, max_length=5, null=True)),
                ('line', models.CharField(blank=True, max_length=40, null=True)),
                ('stop_name', models.CharField(blank=True, db_column='stop name', max_length=255, null=True)),
                ('borough', models.CharField(blank=True, max_length=2, null=True)),
                ('daytime_routes', models.CharField(blank=True, db_column='daytime routes', max_length=20, null=True)),
                ('structure', models.CharField(blank=True, max_length=20, null=True)),
                ('gtfs_latitude', models.DecimalField(blank=True, db_column='gtfs latitude', decimal_places=65535, max_digits=65535, null=True)),
                ('gtfs_longitude', models.DecimalField(blank=True, db_column='gtfs longitude', decimal_places=65535, max_digits=65535, null=True)),
                ('north_direction_label', models.CharField(blank=True, db_column='north direction label', max_length=255, null=True)),
                ('south_direction_label', models.CharField(blank=True, db_column='south direction label', max_length=255, null=True)),
            ],
            options={
                'db_table': 'stations',
                'managed': False,
            },
        ),
    ]
