# Generated by Django 3.1.7 on 2021-04-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCounts2019',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('daytime_routes', models.CharField(blank=True, max_length=20, null=True)),
                ('division', models.CharField(blank=True, max_length=5, null=True)),
                ('line', models.CharField(blank=True, max_length=40, null=True)),
                ('borough', models.CharField(blank=True, max_length=2, null=True)),
                ('structure', models.CharField(blank=True, max_length=20, null=True)),
                ('gtfs_latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('gtfs_longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('complex_id', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('entries', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('exits', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'daily_counts_2019',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyCounts2020',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('daytime_routes', models.CharField(blank=True, max_length=20, null=True)),
                ('division', models.CharField(blank=True, max_length=5, null=True)),
                ('line', models.CharField(blank=True, max_length=40, null=True)),
                ('borough', models.CharField(blank=True, max_length=2, null=True)),
                ('structure', models.CharField(blank=True, max_length=20, null=True)),
                ('gtfs_latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('gtfs_longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('complex_id', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('entries', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('exits', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'daily_counts_2020',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyCounts2021',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('daytime_routes', models.CharField(blank=True, max_length=20, null=True)),
                ('division', models.CharField(blank=True, max_length=5, null=True)),
                ('line', models.CharField(blank=True, max_length=40, null=True)),
                ('borough', models.CharField(blank=True, max_length=2, null=True)),
                ('structure', models.CharField(blank=True, max_length=20, null=True)),
                ('gtfs_latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('gtfs_longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('complex_id', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('entries', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('exits', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'daily_counts_2021',
                'managed': False,
            },
        ),
    ]
