# Generated by Django 3.1.7 on 2021-04-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dailycounts2019_dailycounts2020_dailycounts2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyCounts2020',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('total_year_entries', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('total_year_exits', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'yearly_counts_2020',
                'managed': False,
            },
        ),
    ]
