# Generated by Django 3.1.7 on 2021-04-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_yearlycounts2019_yearlycounts2021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YearlyCounts2019',
        ),
        migrations.DeleteModel(
            name='YearlyCounts2020',
        ),
        migrations.DeleteModel(
            name='YearlyCounts2021',
        ),
    ]
